USE sirec;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE PAGOS;
TRUNCATE TABLE DETALLE_RECETAS;
TRUNCATE TABLE RECETAS;
TRUNCATE TABLE EXPEDIENTE_CONSULTA;
TRUNCATE TABLE TRIAJES_SIGNOS;
TRUNCATE TABLE CITA;
TRUNCATE TABLE USUARIOS;
TRUNCATE TABLE EMPLEADOS;
TRUNCATE TABLE PACIENTES;
TRUNCATE TABLE MEDICAMENTOS;
TRUNCATE TABLE CATALOGO_CIE10;
TRUNCATE TABLE ESPECIALIDADES;
TRUNCATE TABLE ROLES;

SET FOREIGN_KEY_CHECKS = 1;
